
services:
  application:
    build:
      dockerfile: Dockerfile
    container_name: laravel_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - laravel_app:/var/www/html
    depends_on:
      - postgres
    command: sh -c "php artisan config:clear && php artisan serve --host=0.0.0.0 --port=8000"

  postgres:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: unicarona
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  laravel_app:  
  postgres_data:
